### ISSUE TITLE
What is slice_and_move_batch_for_device() supposed to do?

### ISSUE THREAD

**Issue by Tony363** [eric-mitchell/direct-preference-optimization#10]
I am getting the below errors while running the example from this github readme. 

Step 2:
`python -u train.py model=pythia28 datasets=[hh] loss=sft exp_name=anthropic_dpo_pythia28 gradient_accumulation_steps=20 batch_size=4 eval_batch_size=2 trainer=FSDPTrainer sample_during_eval=false model.fsdp_policy_mp=bfloat16`
Step 3:
`python -u train.py model=pythia28 datasets=[hh] loss=sft exp_name=anthropic_dpo_pythia28 gradient_accumulation_steps=20 batch_size=4 eval_bts=[hh] loss=sft exp_name=anthropic_dpo_pythia28 gradient_accumulation_satch_size=2 trainer=FSDPTrainer sample_during_eval=false model.fsdp_policy_mp=bfloat16`

``Traceback (most recent call last):
  File "/root/direct-preference-optimization/train.py", line 105, in main
    mp.spawn(worker_main, nprocs=world_size, args=(world_size, config, policy, reference_model), join=True)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/root/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/direct-preference-optimization/train.py", line 46, in worker_main
    trainer.train()
  File "/root/direct-preference-optimization/trainers.py", line 299, in train
    _, eval_metrics = self.get_batch_metrics(local_eval_batch, self.config.loss, train=False)
  File "/root/direct-preference-optimization/trainers.py", line 218, in get_batch_metrics
    policy_chosen_logps, policy_rejected_logps = self.concatenated_forward(self.policy, batch)
  File "/root/direct-preference-optimization/trainers.py", line 204, in concatenated_forward
    all_logits = model(concatenated_batch['concatenated_input_ids'], attention_mask=concatenated_batch['concatenated_attention_mask']).logits.to(torch.float32)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 493, in forward
    assert batch_size > 0, "batch_size has to be defined and > 0"
AssertionError: batch_size has to be defined and > 0
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.``

I am checking the output of slice_and_move_batch_for_device() and got the output below;

`{'prompt': [], 'chosen': [], 'rejected': [], 'chosen_response_only': [], 'rejected_response_only': [], 'chosen_input_ids': tensor([], size=(0, 266), dtype=torch.int64), 'chosen_attention_mask': tensor([], size=(0, 266), dtype=torch.int64), 'chosen_labels': tensor([], size=(0, 266), dtype=torch.int64), 'rejected_input_ids': tensor([], size=(0, 272), dtype=torch.int64), 'rejected_attention_mask': tensor([], size=(0, 272), dtype=torch.int64), 'rejected_labels': tensor([], size=(0, 272), dtype=torch.int64), 'prompt_input_ids': tensor([], size=(0, 256), dtype=torch.int64), 'prompt_attention_mask': tensor([], size=(0, 256), dtype=torch.int64)}
`

What is happening? What is the slice_and_move_batch_for_device() function supposed to do?

Even more specifically, what is the supposed chunk size if I have 3 gpus? is the chunk size relative to the batch_size?
` chunk_size = len(list(batch.values())[0]) // world_size`

**Comment by Tony363** [comment]
Nvm, I found out the chunk_size is just the number of batches divided by the GPUs available. Batch size just need to be greater than the number of GPUs

**Comment by eric-mitchell** [comment]
It looks like you've changed `grad_accumulation_steps` to 20 (it is 2 in the example commands in the README). You can't have `grad_accumulation_steps` > `batch_size` (we accumulate over microbatches of size `batch_size / grad_accumulation_steps`). It also looks like you have an extra arg `gradient_accumulation_satch_size`, which isn't an argument supported by our trainers.

`slice_and_move_batch_for_device` gives a sub-slice of a batch based on a chunk index and total number of chunks, then moves the sub-sliced batch onto the given device. This function is useful for both FSDP sub-slicing and grad accumulation.

I'll close this, but feel free to re-open if your issue isn't resolved!
