### ISSUE TITLE
Multi-node optimizer save error

### ISSUE THREAD

**Issue by AltenLi** [eric-mitchell/direct-preference-optimization#33]
I'm updating DPO into multi-nodes, 
trans batch into 
```
train_sampler = DistributedSampler(train_dataset,
                                           rank=self.rank,
                                           num_replicas=self.world_size,
                                           seed=self.seed,
                                           shuffle=True)
        self.train_dataloader = DataLoader(train_dataset, sampler=train_sampler, collate_fn=collate_fn,
                                           batch_size=config.batch_size, drop_last=True)
```

but when I using 2 * 8 A100, saving optimizer, the error came:
```
        save_policy = FullOptimStateDictConfig(offload_to_cpu=True, rank0_only=True)
        with FSDP.state_dict_type(self.policy, StateDictType.FULL_STATE_DICT, optim_state_dict_config=save_policy):
            optimizer_state_dict = FSDP.optim_state_dict(self.policy, self.optimizer)
```
```

Traceback (most recent call last):
  File "/search/odin/altenli/direct-preference-optimization/train.py", line 143, in main
    worker_main(config, policy, reference_model)
  File "/search/odin/altenli/direct-preference-optimization/train.py", line 59, in worker_main
    trainer.train()
  File "/search/odin/altenli/direct-preference-optimization/trainers.py", line 457, in train
    self.save(output_dir, mean_eval_metrics)
  File "/search/odin/altenli/direct-preference-optimization/trainers.py", line 631, in save
    optimizer_state_dict = FSDP.full_optim_state_dict(self.policy, self.optimizer)
  File "/search/odin/altenli/dpoenv/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1330, in full_optim_state_dict
    return FullyShardedDataParallel._optim_state_dict_impl(
  File "/search/odin/altenli/dpoenv/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1154, in _optim_state_dict_impl
    return _optim_state_dict(
  File "/search/odin/altenli/dpoenv/lib/python3.9/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1508, in _optim_state_dict
    fsdp_osd["param_groups"] = _unflatten_param_groups(
  File "/search/odin/altenli/dpoenv/lib/python3.9/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1311, in _unflatten_param_groups
    nested_unflat_param_names = [
  File "/search/odin/altenli/dpoenv/lib/python3.9/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1312, in <listcomp>
    param_to_fqns[param] for param in param_group_params
KeyError: Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0001,  0.0012,  0.0003,  ...,  0.0006,  0.0011,  0.0003],
        [ 0.0009,  0.0074, -0.0137,  ...,  0.0053,  0.0146,  0.0013],
        ...,
        [-0.0043, -0.0063,  0.0071,  ..., -0.0029, -0.0024, -0.0065],
        [-0.0015, -0.0015, -0.0015,  ..., -0.0037, -0.0009, -0.0010],
        [ 0.0060, -0.0078,  0.0006,  ..., -0.0086,  0.0082, -0.0028]],
       device='cuda:0', dtype=torch.bfloat16, requires_grad=True)
```
 I've been searched, but no answer found. Could you help me?

**Comment by AltenLi** [comment]
I'm using torchrun and changed some code to fit torchrun.
single-node result is normal like the master branch/

**Comment by AltenLi** [comment]
emm.Seems like single-node is not work too..

**Comment by AltenLi** [comment]
that's my fault....
I moved 
'''
 self.optimizer = getattr(torch.optim, self.config.optimizer)(self.policy.parameters(), lr=self.config.lr)
        self.scheduler = torch.optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=lambda step: min(1.0,
                                                                                                      (step + 1) / (
                                                                                                                  self.config.warmup_steps + 1)))
'''
into BasicTrainer.__init__

**Comment by eric-mitchell** [comment]
Thanks for looking into this! Have you resolved the multi-node issues as well, or just the single node problem?

**Comment by AltenLi** [comment]
It's solved in 7B, but init policy in 13B will cause OOM.. I'm looking into accelerator + ds for less mem use

**Comment by nxphi47** [comment]
> that's my fault.... I moved ''' self.optimizer = getattr(torch.optim, self.config.optimizer)(self.policy.parameters(), lr=self.config.lr) self.scheduler = torch.optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=lambda step: min(1.0, (step + 1) / ( self.config.warmup_steps + 1))) ''' into BasicTrainer.**init**

Can you please provide the details of your code changes for multi-node dpo ? thanks!
