### ISSUE TITLE
error when following the readme to train sft on multiple cards using FSDPTrainer

### ISSUE THREAD

**Issue by NekoMimiUnagi** [eric-mitchell/direct-preference-optimization#51]
I followed the [complete example](https://github.com/eric-mitchell/direct-preference-optimization#a-complete-example) in readme and got the error: `torch.multiprocessing.spawn.ProcessRaisedException:`

Full logs:
`WARNING: eval_every must be divisible by batch_size
Setting eval_every to 19968
no FSDP port specified; using open port for FSDP: 56131
seed: 0
exp_name: anthropic_dpo_pythia28
batch_size: 64
eval_batch_size: 32
debug: false
fsdp_port: 56131
datasets:
- hh
wandb:
  enabled: true
  entity: null
  project: direct-preference-optimization
local_dirs:
- /scr-ssd
- /scr
- .cache
sample_during_eval: false
n_eval_model_samples: 16
do_first_eval: true
local_run_dir: .cache/rxl190028/anthropic_dpo_pythia28_2023-11-02_19-18-46_430411
lr: 5.0e-07
gradient_accumulation_steps: 2
max_grad_norm: 10.0
max_length: 512
max_prompt_length: 256
n_epochs: 1
n_examples: null
n_eval_examples: 256
trainer: FSDPTrainer
optimizer: RMSprop
warmup_steps: 150
activation_checkpointing: false
eval_every: 19968
minimum_log_interval_secs: 1.0
model:
  name_or_path: EleutherAI/pythia-2.8b
  tokenizer_name_or_path: null
  archive: null
  block_name: GPTNeoXLayer
  policy_dtype: float32
  fsdp_policy_mp: bfloat16
  reference_dtype: float16
loss:
  name: sft

================================================================================
Writing to csr-93596:.cache/rxl190028/anthropic_dpo_pythia28_2023-11-02_19-18-46_430411
================================================================================
building policy
starting 2 processes for FSDP training
setting RLIMIT_NOFILE soft limit to 1048576 from 1024
0 initializing distributed
1 initializing distributed
Creating trainer on process 1 with world size 2
Loading HH dataset (test split) from Huggingface...
wandb: Currently logged in as: rxl190028. Use `wandb login --relogin` to force relogin
Error executing job with overrides: ['model=pythia28', 'datasets=[hh]', 'loss=sft', 'exp_name=anthropic_dpo_pythia28', 'gradient_accumulation_steps=2', 'batch_size=64', 'eval_batch_size=32', 'trainer=FSDPTrainer', 'sample_during_eval=false', 'model.fsdp_policy_mp=bfloat16']
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main()
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 111, in main
    mp.spawn(worker_main, nprocs=world_size, args=(world_size, config, policy, reference_model), join=True)
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/rxl190028/github/dpo/train.py", line 42, in worker_main
    trainer = TrainerClass(policy, config, config.seed, config.local_run_dir, reference_model=reference_model, rank=rank, world_size=world_size)
  File "/home/rxl190028/github/dpo/trainers.py", line 421, in __init__
    super().__init__(policy, config, seed, run_dir, reference_model, rank, world_size)
  File "/home/rxl190028/github/dpo/trainers.py", line 170, in __init__
    self.eval_batches = list(self.eval_iterator)
  File "/home/rxl190028/github/dpo/preference_datasets.py", line 320, in get_batch_iterator
    for prompt, data in get_dataset(name, split, silent=silent, cache_dir=cache_dir).items():
  File "/home/rxl190028/github/dpo/preference_datasets.py", line 168, in get_dataset
    data = get_hh(split, silent=silent, cache_dir=cache_dir)
  File "/home/rxl190028/github/dpo/preference_datasets.py", line 142, in get_hh
    dataset = datasets.load_dataset('Anthropic/hh-rlhf', split=split, cache_dir=cache_dir)
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/home/rxl190028/miniconda3/envs/dpo/lib/python3.8/site-packages/datasets/builder.py", line 1107, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
`

The second error about the dataset package can be solved by upgrading the dataset package to the latest version. But, the first error cannot be solved by upgrading or downgrading the torch version.

**Comment by shossain7757** [comment]
After changing the datasets package version to 2.15.0 it has worked for me.

**Comment by AquaHorseM** [comment]
I faced the same error. Upgrading datasets package to 2.15.0, an error like this occurs:

> datasets.data_files.EmptyDatasetError: The directory at hf://datasets/Anthropic/hh-rlhf@09be8c5bbc57cb3887f3a9732ad6aa7ec602a1fa doesn't contain any data files
