### ISSUE TITLE
Division by Zero error sporadically occurs

### ISSUE THREAD

**Issue by Jayant1234** [eric-mitchell/direct-preference-optimization#78]
On some conifigurations of RAM, GPU, grad_accumulation steps and batch size, the code runs well but throws division by zero error in others. 
More context: I updated transformers to 4.38.1. So that could also cause the issue. 

Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File ".../direct-preference-optimization-main/train.py", line 44, in worker_main
    trainer.train()
  File ".../direct-preference-optimization-main/trainers.py", line 383, in train
    mean_train_metrics = {k: sum(v) / len(v) for k, v in batch_metrics.items()}
  File ".../direct-preference-optimization-main/trainers.py", line 383, in <dictcomp>
    mean_train_metrics = {k: sum(v) / len(v) for k, v in batch_metrics.items()}
ZeroDivisionError: division by zero
Made this adjustment for the time being : mean_eval_metrics = {k: sum(v) / len(v) if len(v) > 0 else 0 for k, v in all_eval_metrics.items()}
Underlying issue is not fixed.

**Comment by Jayant1234** [comment]
The issue is the same as: https://github.com/eric-mitchell/direct-preference-optimization/issues/10
Need to ensure that the effective batch size per GPU = (batch_size)/ (num_gpus*accumulation_steps) is 1 or more or else the chunk size will be 0 and no training or evaluation will happen.
